name: Build Docker (Dev)

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      path_dockerfile:
        description: "dockerfile path in repo"
        required: true
        default: "Dockerfile"
        type: string
      package_app:
        description: "Input package"
        required: true
        default: "cloudflare-warp"
        type: string
      arch_branch:
        description: "Input arch"
        required: true
        default: "linux/amd64,linux/arm64"
        type: string
      dockerhub_repo:
        description: "Docker Hub repository"
        required: true
        default: "grinch27/cloudflare-warp"
        type: string

env:
  TZ: UTC
  path_dockerfile: ${{ inputs.path_dockerfile || 'Dockerfile' }}
  package_app: ${{ inputs.package_app || 'cloudflare-warp' }}
  arch_branch: ${{ inputs.arch_branch || 'linux/amd64,linux/arm64' }}
  dockerhub_repo: ${{ inputs.dockerhub_repo || 'grinch27/cloudflare-warp' }}

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    services:
      registry:
        image: registry:latest
        ports:
          - 5000:5000
    steps:
      - name: Checkout DIY
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: ${{ env.arch_branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@master
        with:
          context: .
          file: ${{ github.workspace }}/${{ env.path_dockerfile }}
          no-cache: false
          platforms: ${{ env.arch_branch }}
          load: false
          push: true
          tags: localhost:5000/${{ env.dockerhub_repo }}:latest
          # labels: ${{ steps.meta.outputs.labels }}

      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/${{ env.dockerhub_repo }}:latest
          docker pull localhost:5000/${{ env.dockerhub_repo }}:latest

      - name: Test Docker image
        id: test
        env:
          image: localhost:5000/${{ env.dockerhub_repo }}:latest
          container_name: ${{ env.package_app }}
        run: |
          # docker run --name ${{ env.container_name }} --rm -d ${{ env.image }} sleep infinity
          docker run \
            --name ${{ env.container_name }} \
            --rm \
            -d \
            ${{ env.image }} \
            /bin/bash -c "uname -a && sleep infinity"

          # List all installed packages
          docker exec ${{ env.container_name }} dpkg -l

          # Execute command in Docker container
          version=$(docker exec ${{ env.container_name }} warp-cli --version | grep 'warp-cli' | awk '{print $2}')
          echo "version=$version"
          echo "version=$version" >> ${GITHUB_OUTPUT}

          # Stop Docker container
          docker stop ${{ env.container_name }}

          # Remove Docker image
          # docker rmi ${{ env.image }}

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Tag and push Docker image with version and architecture
        env:
          version: ${{ steps.test.outputs.version }}
          ARCH_BRANCH: ${{ env.arch_branch }}
        run: |
          for arch in ${ARCH_BRANCH//,/ }
          do
            docker tag localhost:5000/${{ env.dockerhub_repo }}:latest localhost:5000/${{ env.dockerhub_repo }}:${{ env.version }}-$arch
            docker push localhost:5000/${{ env.dockerhub_repo }}:${{ env.version }}-$arch
          done
