name: Build Docker

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
  workflow_dispatch:
    inputs:
      path_dockerfile:
        description: "dockerfile path in repo"
        required: true
        default: "Dockerfile"
        type: string
      package_app:
        description: "Input package"
        required: true
        default: "cloudflare-warp"
        type: string
      arch_branch:
        description: "Input arch"
        required: true
        default: "linux/amd64,linux/arm64"
        type: string
      dockerhub_repo:
        description: "Docker Hub repository"
        required: true
        default: "grinch27/cloudflare-warp"
        type: string

env:
  TZ: UTC
  path_dockerfile: ${{ inputs.path_dockerfile || 'Dockerfile' }}
  package_app: ${{ inputs.package_app || 'cloudflare-warp' }}
  arch_branch: ${{ inputs.arch_branch || 'linux/amd64,linux/arm64' }}
  dockerhub_repo: ${{ inputs.dockerhub_repo || 'grinch27/cloudflare-warp' }}

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    steps:
      - name: Checkout DIY
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: ${{ env.arch_branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get package version
        id: ver
        working-directory: /
        env:
          OS_ARCH: "amd64"
          GPG_KEY_URL: "https://pkg.cloudflareclient.com/pubkey.gpg"
          KEYRING_FILE: "/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg"
          SOURCE_LIST_FILE: "/etc/apt/sources.list.d/cloudflare-client.list"
          PACKAGE_SOURCE_URL: "https://pkg.cloudflareclient.com/"
        run: |
          echo -e "Current working directory: $(pwd)"

          # APT
          sudo -E apt-get -y -qq update
          sudo -E apt-get -y -qq install \
            ca-certificates \
            curl \
            gpg \
            lsb-release

          # Add gpg key
          # OS_ARCH=$(dpkg --print-architecture)
          OS_VER=$(lsb_release -cs)
          curl -fsSL ${GPG_KEY_URL} | gpg --yes --dearmor --output ${KEYRING_FILE}
          echo "deb [signed-by=${KEYRING_FILE}] ${PACKAGE_SOURCE_URL} ${OS_VER} main" | sudo tee ${SOURCE_LIST_FILE}
          sudo -E apt-get -y -qq update

          # apt-cache
          apt-cache show ${{ env.package_app }}
          apt-cache policy ${{ env.package_app }}
          apt-cache showpkg ${{ env.package_app }}
          apt-cache depends ${{ env.package_app }}
          apt-cache rdepends ${{ env.package_app }}
          apt-cache madison ${{ env.package_app }}

          # $GITHUB_ENV
          ver_amd64=$(apt-cache policy ${{ env.package_app }}:${{ env.OS_ARCH }} | grep Candidate: | awk '{print $2}')
          echo "version: $ver_amd64"
          echo "version=$ver_amd64" >> ${GITHUB_OUTPUT}

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.dockerhub_repo }}
          tags: |
            type=raw,value=latest,enabled=true
            type=raw,value=${{ steps.ver.outputs.version }},enabled=true
          flavor: latest=false

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@master
        with:
          context: .
          file: ${{ github.workspace }}/${{ env.path_dockerfile }}
          no-cache: false
          platforms: ${{ env.arch_branch }}
          load: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    name: Test Docker
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test Docker image
        id: test
        env:
          image: ${{ env.dockerhub_repo }}:latest
          container_name: ${{ env.package_app }}
        run: |
          # Run Docker container
          docker run --name ${{ env.container_name }} --rm -d ${{ env.image }} sleep infinity

          # Execute command in Docker container
          docker exec ${{ env.container_name }} warp-cli --version | tee /dev/stderr | grep 'warp-cli'

          # Stop Docker container
          docker stop ${{ env.container_name }}

          # Remove Docker image
          docker rmi ${{ env.image }}

          echo "status=success" >> ${GITHUB_OUTPUT}
